services:
  notification_for_jeby:
    image: docker pull ghcr.io/jeby-228/notification_for_jeby:latest
    container_name: notification_for_jeby
    restart: unless-stopped
    ports:
      - '${PORT:-8080}:8081'
    environment:
      - PORT=${PORT:-8080}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - JWT_SECRET=${JWT_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - notification_for_jeby_network
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  watchtower:
    image: containrrr/watchtower:latest
    container_name: notification_for_jeby_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_ENABLE}
      - WATCHTOWER_INCLUDE_RESTARTING=${WATCHTOWER_INCLUDE_RESTARTING}
    networks:
      - notification_for_jeby_network

networks:
  notification_for_jeby_network:
    driver: bridge
