version: '3.8'

services:
  member_api:
    image: ghcr.io/jebylinjbjob/member_api:latest
    container_name: member_api
    restart: unless-stopped
    ports:
      - '${PORT:-8080}:8081'
    environment:
      - POSTGRES_DSN=${POSTGRES_DSN}
      - JWT_SECRET=${JWT_SECRET}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - member_api_network
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  watchtower:
    image: containrrr/watchtower:latest
    container_name: member_api_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_ENABLE}
      - WATCHTOWER_INCLUDE_RESTARTING=${WATCHTOWER_INCLUDE_RESTARTING}
    networks:
      - member_api_network

networks:
  member_api_network:
    driver: bridge
